global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "apps"
    dns_sd_configs:
      - names:
          - app
        type: A
        port: 5000

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
